/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "main.h"


void make_all_rows_high(void);
void delay (void);


int main(void)
{//ENABLE RCC FOR PORTX
	GPIOX_AHB1ENR->gpiod_en = ENABLECLOCK;
	GPIOX_AHB1ENR->gpioc_en = ENABLECLOCK;

//FOR LED
//ENABLE MODE PD11 AND PD12 AS OUTPUT
	GPIOX_MODEREG_D->moder11 &= CLEAR_PD11;
	GPIOX_MODEREG_D->moder11 |= SET_PD11_AS_OUTPUT;

	GPIOX_MODEREG_D->moder12 &= CLEAR_PD12;
	GPIOX_MODEREG_D->moder12 |= SET_PD12_AS_OUTPUT;

//FOR KEYPADS
//ENABLE MODE PC0 AND PC1 AS OUTPUT
	GPIOX_MODEREG_C->moder0 &= CLEAR_PC0;
	GPIOX_MODEREG_C->moder0 |= SET_PC0_AS_OUTPUT;

	GPIOX_MODEREG_C->moder1 &= CLEAR_PC1;
	GPIOX_MODEREG_C->moder1 |=SET_PC1_AS_OUTPUT;

//ENABLE MODE PC2 AND PC3 AS INPUT
	GPIOX_MODEREG_C->moder2 &= SET_PC2_AS_INPUT;

	GPIOX_MODEREG_C->moder3 &= SET_PC3_AS_INPUT;

//ENABLE PUSHUP RESISTOR PC2 AND PC3 AS PUPDR
	GPIOX_PUPDR_C->pupdr2 &= CLEAR_PC2_PUPDR;
	GPIOX_PUPDR_C->pupdr2 |= SET_PC2_AS_PUPDR;

	GPIOX_PUPDR_C->pupdr3 &= CLEAR_PC3_PUPDR;
	GPIOX_PUPDR_C->pupdr3 |= SET_PC3_AS_PUPDR;



    /* Loop forever */
	while(1){

//MAKE ALL ROWS HIGH (PC0 AND PC1 AS OUTPUT)
		make_all_rows_high();
//MAKE ROW1(PC0) LOW
		SET_ROW1_LOW;

//SCAN THE COLUMNS()
		if(COLUMN_1_ENABLE){    //TURN ON LED_1
			delay();
			TURN_ON_LED_1;
			delay();
			TURN_OFF_LED_1;      //TURN OFF LED_1

		}

		if(COLUMN_2_ENABLE){     //TURN ON LED_2
			delay();
			TURN_ON_LED_2;
			delay();
			TURN_OFF_LED_2;  //TURN OFF LED_1

			}



//MAKE ALL ROWS HIGH (PC0 AND PC1 AS OUTPUT)
		make_all_rows_high();
//MAKE ROW2(PC1) LOW
		SET_ROW2_LOW;

//SCAN THE COLUMNS()
		if(COLUMN_1_ENABLE){    //TURN ON LED_1
			delay();
			TURN_ON_LED_1;
			delay();
			TURN_OFF_LED_1;      //TURN OFF LED_1

		   }

		if(COLUMN_2_ENABLE){     //TURN ON LED_2
			delay();
			TURN_ON_LED_2;
			delay();
			TURN_OFF_LED_2;  //TURN OFF LED_1

			}

	}
}


void make_all_rows_high(void){
	GPIOX_ODREG_C->odr0 |=  (1);

	GPIOX_ODREG_C->odr1 |=  (1);
}

void delay (void){                    //approximately 150us
	for(int i = 0; i < 300000; i++);
}
